import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Docbar from "@/components/layout/Navbar";
const inter = Outfit({ subsets: ["latin"] });
import { ThemeProvider } from "@/components/theme-provider";
export const metadata: Metadata = {
	title: "Souvik karmakar",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ThemeProvider
					attribute="class"
					defaultTheme="dark"
					enableSystem
					disableTransitionOnChange
				>
					<div className="fixed bottom-10 left-1/2 -translate-x-1/2 z-50">
						<Docbar />
					</div>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
